### ISSUE TITLE
Terrain modeling in ERF

### ISSUE THREAD

**Issue by indra098124** [erf-model/ERF#1047]
Hi, 

I would like to explore ERF to study the effect of terrains in LES. May I ask how do I include terrain in ERF simulations? Is there any example I can look at? How do I give latitude, longitude in an ERF simulation and how to get initial conditions from a global database (ERA5, NCEP etc).

My apologies for posting this as an issue instead of discussion. This is because there is no discussion section on the ERF github page.
Thank you

**Comment by asalmgren** [comment]
Thank you for your interest!  Unfortunately ERF is still under active development so we aren't yet supporting external users.  We plan to have ERF available for use starting in October 2023.

**Comment by oriollacave** [comment]
Hi,
I think there was a presentation this year in Austin. Is there any news about this? I would be also interested in testing the features with real terrain.
Thank you
