### ISSUE TITLE
Implement one-way coupling to AMR-Wind using ERF's NetCDF output.

### ISSUE THREAD

**Issue by dwillcox** [erf-model/ERF#125]
- [x] 1D column one-way coupling
- [ ] 2D plane one-way coupling

**Comment by dwillcox** [comment]
Assigned to Bruce Perry

**Comment by dwillcox** [comment]
Checkpoint files include ghost zones and all other information needed to restart. We can use these for the coupling.

**Comment by wgustafson** [comment]
Hi, quick suggestion... The checkpoint files could serve as a temporary approach for transferring information for offline coupling to AMR-Wind. However, it would not be a good long-term approach. Coupling would typically need to occur very frequently (on the order of minutes in the model's time), whereas checkpoints are more for safety and doing model restarts (on the order of 6 wall hours). The checkpoint files contain way more information than necessary for doing the coupling, so outputting them frequently enough to do the coupling would be highly inefficient and slow down the model. So, you need a separate output stream for coupling and general model output, separate from the checkpoints.

I don't know how you've been thinking about this, and you might already know this. But I thought I'd mention this to keep the development on a useful track.

**Comment by dwillcox** [comment]
Thanks @wgustafson for pointing out how unwieldy checkpoint files can be going forwards! That's a great point.

In that case it sounds like the first task for @baperry2 is to figure out what information we need from ERF and whether this already exists in the output files or we need to add it.

As a first pass just to pick out the information we need and sanity check that AMR-Wind can run with it, maybe a checkpoint file would be good as a reference. Then we can restrict ourselves to just the needed data.

**Comment by wgustafson** [comment]
Sounds like a good plan. In general, having a way to easily define different output streams is really useful. Coupling is one example, but there are also many times users want to output different variables at different frequencies. For example, winds an cloud fields (when we get that sort of thing) output every minute for a period of a run to use for 3-D animations whereas the bulk of the fields are only output every 15 min. If this could be developed at the same time as the coupling output, it would save time in the end.

**Comment by asalmgren** [comment]
@dwillcox -- maybe we should add to the "wish list" the ability to output different variables at different frequencies in netcdf format -- we can move it forward depending on how things go?

**Comment by wgustafson** [comment]
This is not something that would have to be in he first beta release, so to speak. But, we would want it in v1. It could come next year. Laying the foundation in the core code infrastructure is the key point.

**Comment by asalmgren** [comment]
Finished by Bruce Perry!
