### ISSUE TITLE
MOST + grid stretching (terrain) can give unexpected surface fluxes

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#1273]
Example input:
```
erf.use_terrain = true
erf.terrain_z_levels = 0 5 10.125 # ...
```
and in Problem::init_custom_terrain(): `z_phys_nd.setVal(0.0);`

Problem arises here:
https://github.com/erf-model/ERF/blob/f7c653cf2eb028bdee7d7dcd6793a6e1ff079377/Source/BoundaryConditions/ABLMost.cpp#L109-L121
If there is grid stretching, then there is no guarantee that dz at the surface is equal to the grid spacing specified by `geometry.prob_extent` and `amr.n_cell`. 

A workaround is to set zhi such that geom[lev].CellSize(2) is equal to the dz at the first level; the actual top of the domain would be dictated by the last erf.terrain_z_levels value.

**Comment by AMLattanzi** [comment]
I believe this should be addressed with [PR 1275](https://github.com/erf-model/ERF/pull/1275).
