### ISSUE TITLE
Implementation of terrain grid with STF smoothing

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#1368]
https://github.com/erf-model/ERF/blob/1b743c756a10f59847e65d181517641b061ace15/Source/Utils/TerrainMetrics.cpp#L205-L210

Appears to follow Eqns 11 and 9 from Klemp 2011 (https://journals.ametsoc.org/view/journals/mwre/139/7/mwr-d-10-05046.1.xml), respectively. However, line 205 is missing any dependence on the actual terrain, i.e., the maximum terrain height (max_h).

**Comment by AMLattanzi** [comment]
@ewquon I agree with your findings and will test this modification on the WOA problem to verify it generates an appropriate grid.

**Comment by AMLattanzi** [comment]
Original code (left) compared to the suggested modification (right). Not a large change in the constructed grid but the code will be modified for consistency with the reference source.
![image](https://github.com/erf-model/ERF/assets/103702284/c252f68e-2ddb-45e7-abde-f5c8a36676d1)

**Comment by ewquon** [comment]
I imagined you'd see a larger difference if you, say, doubled the height of the hill.

**Comment by AMLattanzi** [comment]
[PR1377](https://github.com/erf-model/ERF/pull/1377) should address this issue.

**Comment by AMLattanzi** [comment]
See [PR 1377](https://github.com/erf-model/ERF/pull/1377) where correction was made.

**Comment by ewquon** [comment]
Fixed in #1807, including divide by 0 handling (encountered when STF smoothing is applied with flat terrain)
