### ISSUE TITLE
Organize ERF source code into a library

### ISSUE THREAD

**Issue by rafmudaf** [erf-model/ERF#142]
Reorganize the CMake project and `Source` directory so that ERF is compiled into library and this is linked to any executables

**Comment by rafmudaf** [comment]
The work I did to reorganize the ERF source code into a library is in this branch: https://github.com/rafmudaf/erf/tree/add_testing. See the last few commits to understand the process and progress.
cc @rfhaque

**Comment by dwillcox** [comment]
A general setup that can run most problems would make the initialization more elegant.

Could benefit from the code parser Weiqun wrote for WarpX: https://github.com/WeiqunZhang/WarpXParser

**Comment by asalmgren** [comment]
@dwillcox -- My understanding is that this issue is completely independent (at this point) of using the parser -- this doesn't change anything about the problem setups...

**Comment by asalmgren** [comment]
This was completed by Jean Sexton
