### ISSUE TITLE
Document boundary conditions and any boundary condition tests.

### ISSUE THREAD

**Issue by dwillcox** [erf-model/ERF#146]

**Comment by dwillcox** [comment]
@pkjha-aero did you bring this up? Can you fill in the details here?

**Comment by pkjha-aero** [comment]
BC implementation was mostly done by @xyuan, @rfhaque, and @brigaudet

**Comment by pkjha-aero** [comment]
> BC implementation was mostly done by @xyuan, @rfhaque, and @brigaudet

I'll document what I understand and get it verified by the implementers.
