### ISSUE TITLE
Set up doxygen for ERF

### ISSUE THREAD

**Issue by dwillcox** [erf-model/ERF#165]
- [ ] get doxygen running and integrated with our online docs (Erik Palmer can do this)
- [ ] go through ERF and add proper docstrings to all our functions

**Comment by etpalmer63** [comment]
Still working on the website update on push. PR #171 makes some changes to Doxygen output configuration (which can be changed according to preference). I was also able to modify some comments in the code to better make use of Doxygen's features. 

The structure of the file: `Source/RK3/RK3.H` would make it a good Doxygen example if it were fully documented.

**Comment by asalmgren** [comment]
Doxygen has been set up for ERF and we are adding annotation.  Closing this now.
