### ISSUE TITLE
netcdf_par.h with ubuntu

### ISSUE THREAD

**Issue by loisdmln** [erf-model/ERF#1696]
I had problems while compiling the file cmake_with_netcdf.sh as it couldn't access the file netcfd_par.h.  It seems that the netcdf_mpi library is not installed in the same place ( /usr/lib/x86_64-linux-gnu/netcdf/mpi/include ) as the standard netcdf library (usr/include/ ).

I saw that the WW3 submodule used another FindNetCDF.cmake file to compile the code, but without success.

I finally managed to compile the code by manually moving the netcdf_par.h file from the mpi folder to usr/include, which worked. This problem seems to be a bug between netcdf serial and netcdf parallele.

**Comment by hgopalan** [comment]
I always built netCDF separately and link it to ERF and never use the default libraries which come with the Linux distro. You may want to set PKG_CONFIG_PATH to the location of the pkg_config_path folder of netCDF before compiling. This way any find utility will be able to locate those libraries.

**Comment by loisdmln** [comment]
It works, thank you.
