### ISSUE TITLE
Refactor RK3/EddyViscosity code, precalculate indices

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#22]
@pkjha-aero Is it possible to refactor this code and make a subroutine to precalculate the indexes before calling the nut routine at the end? This would allow reuse of the switch case logic at multiple places in the code.

_Originally posted by @rfhaque in https://github.com/erf-model/ERF/pull/20#discussion_r645699800_

**Comment by pkjha-aero** [comment]
This issue is redundant. The discussion arose because of an incomplete placeholder code where all the indices in switch cases were the same.
