### ISSUE TITLE
Add READMEs for test problems

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#23]
The three new demos `IsentropicVortex`, `ScalarAdvecUniformU` and `ScalarAdvecUniformUV` need README files explaining the problem solved and the corresponding references (if any, such as [this](https://github.com/zzwz02/ERF/blob/BenchmarkExample/Exec/ScalarDiffusion/README) and [this](https://github.com/zzwz02/ERF/blob/BenchmarkExample/Exec/TaylorGreen/README)).

_Originally posted by @zzwz02 in https://github.com/erf-model/ERF/issues/20#issuecomment-854260561_

**Comment by dwillcox** [comment]
Looks like the only problems in Exec with Readme's are:

```
TaylorGreenVortex
ScalarDiffusionSine
ScalarAdvecRigidRot
```

So there are still lots more readme's needed to explain the setups.
