### ISSUE TITLE
Factor of 2 with Smagorinsky

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#62]
Our strain rate calculation returns symmetric stress tensor components, i.e., one-half of du_i/dx_j + du_j/dx_i. Therefore, there should be a factor of 2 in front of the eddy diffusivity term when running Smagorinsky, consistent with the DNS mode. (E.g., Wyngaard2004 Eqn. 9 has tau_ij = K(du_i/dx_j + du_j/dx_i), but the D_ij tensor does not have the factor of one-half like ours does.

From Brian: 
> Thought I checked this and seemed OK.  Needs to be checked carefully in the ERF equation discretization outline.  It seems like the 1/2 is absorbed in some of the averaging. (i.e.,  there could be ( (u(i+1,j) - u(i,j)) + (u(i+1,j+1) - u(i,j+1)) ) which is grid cell interpolation averaging; there should be a factor of 1/2 in the average, but this cancels the 2.

**Comment by asalmgren** [comment]
It would be good to resolve this -- what is our current thinking?

**Comment by asalmgren** [comment]
@ewquon -- do you currently think you or Brian is correct here?

**Comment by pkjha-aero** [comment]
I think the two are consistent. `K (i, j, k)` does have a factor of 2 making it analogous to 2*mu for DNS.

**Comment by pkjha-aero** [comment]
https://github.com/erf-model/ERF/blob/development/Source/RK3/Diffusion.cpp#L34-L38
https://github.com/erf-model/ERF/blob/development/Source/RK3/EddyViscosity.cpp#L76

**Comment by asalmgren** [comment]
@ewquon -- are you in agreement with Pankaj that all is correct?  If so let's close this issue

**Comment by ewquon** [comment]
Okay, I missed https://github.com/erf-model/ERF/blob/8bc67d9ad84b3b31b9ab524fb946b5590055fdb5/Source/RK3/EddyViscosity.cpp#L75-L76 the last time around. It is consistent with Eqn 5 at http://www.scholarpedia.org/article/Turbulence:_Subgrid-Scale_Modeling, with the addition of the `cell_data` density term. 

The sign is correct since diffusion on the RHS should be positive and the contributions are positive:
https://github.com/erf-model/ERF/blob/8bc67d9ad84b3b31b9ab524fb946b5590055fdb5/Source/RK3/RK3_stage.cpp#L204
https://github.com/erf-model/ERF/blob/8bc67d9ad84b3b31b9ab524fb946b5590055fdb5/Source/RK3/RK3_stage.cpp#L232
https://github.com/erf-model/ERF/blob/8bc67d9ad84b3b31b9ab524fb946b5590055fdb5/Source/RK3/RK3_stage.cpp#L260
