### ISSUE TITLE
Fix failing CUDA issues (rand()...) and re-enable the tests in GitHub Actions

### ISSUE THREAD

**Issue by pkjha-aero** [erf-model/ERF#67]
See this PR: https://github.com/erf-model/ERF/pull/66

**Comment by rafmudaf** [comment]
@pkjha-aero This is one of the build errors I see in GitHub Actions: https://github.com/erf-model/ERF/runs/3635121242?check_suite_focus=true#step:5:520.

```
/home/runner/work/ERF/ERF/Source/RK3/RK3_stage.cpp(200): error: calling a __host__ function("std::__cxx11::basic_string<char,  ::std::char_traits<char> , std::allocator<char> > ::compare const") from a __device__ function(" const") is not allowed
```

Is this related to `rand()`? I have no context here so just trying to get some info.

**Comment by rfhaque** [comment]
@rafmudaf It appears the C++ string constructor is being invoked from within the GPU code. Since the standard string constructor only has a CPU implementation, the compiler complains. This issue is analogous to rand().

**Comment by rfhaque** [comment]
We'll need to replace the string invocation with something GPU compatible.

**Comment by ewquon** [comment]
So is the problem with this line? https://github.com/erf-model/ERF/blob/development/Source/DataStruct.H#L13

**Comment by pkjha-aero** [comment]
I think using `std::string` itself is not a problem. We have had other instances of it. But, this particular message is about using `compare` and `const`
