### ISSUE TITLE
Arithmetic error in Couette flow problem compiled in debug mode

### ISSUE THREAD

**Issue by rafmudaf** [erf-model/ERF#70]
The Couette flow problem errors when compiled in debug mode with the following error:
```
Erroneous arithmetic operation
```

Running this case in the debugger shows an error at 
```cpp
    case AdvectedQuantity::v: //y-momentum, reference face index is (i, j, k)
      switch (advectingQuantity) {
      case AdvectingQuantity::rho_u:
        advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::x, spatial_order); // v(i+1/2,    j, k    )
        advectingQty = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j-1, k)); // Effectively rho_u (i+1, j-1/2, k)
        break;
      case AdvectingQuantity::rho_v:
        advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::y, spatial_order); // v(i   , j+1/2, k    )
->      advectingQty = 0.5 * ( rho_v(i, j+1, k) + rho_v(i, j, k) ); // Effectively rho_v (i, j+1/2, k)
        break;
      case AdvectingQuantity::rho_w:
        advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::z, spatial_order); // v(i   , j    , k+1/2)
        advectingQty = 0.5*(rho_w(i, j, k+1) + rho_w(i, j-1, k+1)); // Effectively rho_w (i, j-1/2, k+1)
        break;
      default:
        amrex::Abort("Error: Advecting quantity is unrecognized");
      }
      break;
```

The problem size and geometry inputs are:
```
# PROBLEM SIZE & GEOMETRY
geometry.is_periodic = 1 0 1
geometry.coord_sys   = 0  # 0 => cart, 1 => RZ  2=>spherical
geometry.prob_lo     =  0     0     0
geometry.prob_hi     = 32     16    4    
amr.n_cell           = 32     16    4
```

And the variable values when the error raises are as follows:
```
i: 0
j: 16
k: 0
rho_u: {
  begin: {
    -1, -1, -1
  },
  end: {
    34, 17, 5
  }
}
rho_v: {
  begin: {
    -1, -1, -1
  },
  end: {
    33, 18, 5
  }
}
rho_w: {
  begin: {
    -1, -1, -1
  },
  end: {
    33, 17, 6
  }
}
```

Here's a screenshot of the error caught in the debugger:
<img width="1904" alt="Screen Shot 2021-09-22 at 4 43 18 PM" src="https://user-images.githubusercontent.com/13797903/134426083-2d2db200-3025-41e6-9c18-4f92ab71c4ac.png">

**Comment by pkjha-aero** [comment]
My observations:
1. In debugger: CRASHES in all of {Release, Debug, RelWithDebInfo} mode
2. Command line: RUNS in {Release, Debug, RelWithDebInfo} modes
3. Command Line: ctest passes in {Release, RelWithDebInfo} but fails in Debug mode

**Comment by rafmudaf** [comment]
@pkjha-aero Just to add to your data points, running the Couette flow case in the command line in debug mode does fail for me:

```
(base) >>mbp@~/Development/ERF/Build (development *$)$ /Users/rmudafor/Development/ERF/Build/Exec/CouetteFlow/erf_couette_flow /Users/rmudafor/Development/ERF/Build/Tests/test_files/CouetteFlow/CouetteFlow.i
AMReX (21.03-61-gf9216a341e51) initialized

Starting run at 22:02:12 UTC on 2021-09-23.
Successfully read inputs file ... 

ERF git hash: 4ddcf20a1d6c-dirty
AMReX git hash: 21.03-61-gf9216a341e51

DIR IS INTERIOR 0
DIR IS INTERIOR 0
Dirichlet selected for DIM=1 lower/upper=1 fixedvalue=2 0 0
DIR IS INTERIOR 2
DIR IS INTERIOR 2
Successfully read inputs file ... 
Starting to call amrex_probinit ... 
Successfully run amrex_probinit
Initializing the data at level 0
Done initializing level 0 data 

TIME= 0 MASS        = 2048
INITIAL GRIDS 
  Level 0   1 grids  2048 cells  100 % of domain

PLOTFILE: file = plt00000
writePlotFile_00
Write plotfile time = 0.005597  seconds

[Level 0 step 1] ADVANCE with dt = 0.1
Erroneous arithmetic operation
(base) >>mbp@~/Development/ERF/Build (development *$)$ echo $?
1
```

**Comment by ewquon** [comment]
I've been testing cmake "debug" builds from the command line and they've been crashing, like Raf's case. I've attached the
[Backtrace.0.txt](https://github.com/erf-model/ERF/files/7228234/Backtrace.0.txt), which provides more of the same information.
 
Some additional findings, comparing my Debug build with my Release build:
* The FAB box dimensions match inside of `BCBase` (note that `amr.n_cell = 32 16 4`)
```
x-vel box: ((-1,-1,-1) (33,16,4) (1,0,0))
y-vel box: ((-1,-1,-1) (32,17,4) (0,1,0))
z-vel box: ((-1,-1,-1) (32,16,5) (0,0,1))
```
* The array sizes (begin, end) match in `RK3stage`, even though they're **1 larger than expected** on the high end than I would expect
```
rho_u begin: (-1,-1,-1) end: (34,17,5)
rho_v begin: (-1,-1,-1) end: (33,18,5)
rho_w begin: (-1,-1,-1) end: (33,17,6)
```
* The "Erroneous arithmetic operation" is because `rho_v(i, j, k)` evaluates to nan in the debug case
* Switching from `Dirichlet` to `NoSlipWall` **does NOT give the arithmetic error**
* Defining `phys_bcs::BCBase** bc_rec` can be bad practice; but replacing with `amrex::Vector<std::unique_ptr<phys_bcs::BCBase> >` did not make a difference.
