### ISSUE TITLE
MPI+CUDA CI

### ISSUE THREAD

**Issue by ewquon** [erf-model/ERF#73]
Add CI workflow with `-DERF_ENABLE_MPI:BOOL=ON` in addition to `-DERF_ENABLE_CUDA:BOOL=ON`, to replicate @rfhaque's issue on Lassen HPC.

**Comment by rfhaque** [comment]
Found this related issue with AMReX

https://github.com/ECP-WarpX/WarpX/issues/1132

**Comment by rfhaque** [comment]
@ewquon @pkjha-aero Using cmake-3.16 or higher resolves this issue on lassen. We should upgrade our CI builds to use higher cmake-v3.16+.

**Comment by dwillcox** [comment]
As of #1051 we now build our CUDA CI test on Github with MPI enabled, i.e. with `-DERF_ENABLE_MPI:BOOL=ON` as @ewquon mentioned.
